const employees = [
  {
    id: 1,
    firstName: "Aarav",
    email: "e@e.com",
    password: "123",
    taskCount: { active: 1, newTask: 1, completed: 1, failed: 0 },
    tasks: [
      {
        title: "Design Landing Page",
        description: "Create wireframes for the new marketing site.",
        date: "2025-07-18",
        category: "Design",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix Header Bug",
        description: "Resolve sticky header issue on scroll.",
        date: "2025-07-15",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Prepare Presentation",
        description: "Slides for upcoming client meeting.",
        date: "2025-07-19",
        category: "Meetings",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    firstName: "Ishaan",
    email: "employee2@example.com",
    password: "123",
    taskCount: { active: 1, newTask: 1, completed: 1, failed: 1 },
    tasks: [
      {
        title: "Database Backup",
        description: "Perform weekly backup of customer data.",
        date: "2025-07-16",
        category: "Maintenance",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "API Integration",
        description: "Integrate payment gateway into the app.",
        date: "2025-07-20",
        category: "Development",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Write Unit Tests",
        description: "Add test cases for user module.",
        date: "2025-07-17",
        category: "Testing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Fix Login Issue",
        description: "Resolve 500 error on login attempt.",
        date: "2025-07-14",
        category: "Bug Fixing",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 3,
    firstName: "Vihaan",
    email: "employee3@example.com",
    password: "123",
    taskCount: { active: 1, newTask: 1, completed: 1, failed: 0 },
    tasks: [
      {
        title: "Update Docs",
        description: "Revise API documentation with latest endpoints.",
        date: "2025-07-18",
        category: "Documentation",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Team Meeting",
        description: "Weekly sync-up with the development team.",
        date: "2025-07-19",
        category: "Meetings",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Push UI Updates",
        description: "Deploy new UI components to staging.",
        date: "2025-07-17",
        category: "Deployment",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    firstName: "Anaya",
    email: "employee4@example.com",
    password: "123",
    taskCount: { active: 2, newTask: 0, completed: 1, failed: 1 },
    tasks: [
      {
        title: "Content Review",
        description: "Review blog drafts before publishing.",
        date: "2025-07-15",
        category: "Content",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Fix SEO Issues",
        description: "Address meta tag warnings from audit.",
        date: "2025-07-18",
        category: "SEO",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Research Trends",
        description: "Gather data on UI trends for Q3 planning.",
        date: "2025-07-20",
        category: "Research",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Client Feedback",
        description: "Consolidate and document client input.",
        date: "2025-07-14",
        category: "Feedback",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 5,
    firstName: "Kavya",
    email: "employee5@example.com",
    password: "123",
    taskCount: { active: 3, newTask: 0, completed: 1, failed: 1 },
    tasks: [
      {
        title: "DevOps Setup",
        description: "Configure CI/CD pipelines for new repo.",
        date: "2025-07-17",
        category: "DevOps",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Security Scan",
        description: "Run vulnerability scanner and log issues.",
        date: "2025-07-16",
        category: "Security",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Update Dependencies",
        description: "Upgrade outdated npm packages.",
        date: "2025-07-19",
        category: "Maintenance",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Refactor Code",
        description: "Clean up old modules and improve structure.",
        date: "2025-07-18",
        category: "Development",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Write Blog Post",
        description: "Document lessons learned from recent sprint.",
        date: "2025-07-19",
        category: "Content",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 100,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
